### ISSUE TITLE
Improve chart performance 

### ISSUE THREAD

**Issue by th0mk** [Bitl/FMBot_Discord#48]
Big charts can take quite a while to generate, up to over a minute long. 
Maybe smaller images for bigger charts would help.

**Comment by th0mk** [comment]
this might be a solution: https://stackoverflow.com/questions/12337671/using-async-await-for-multiple-tasks

get multiple images at the same time

**Comment by g--o** [comment]
My pull request should've partially fix this.
Further performance analysis should be made though.

**Comment by th0mk** [comment]
Chart performance has been improved and deadlocking is no longer an issue.
