### ISSUE TITLE
change "total tracks" to "total scrobbles"

### ISSUE THREAD

**Issue by ssteveenn** [Bitl/FMBot_Discord#53]
tracks may be misunderstood as individual tracks/songs

**Comment by Bitl** [comment]
that's exactly what they are though.

**Comment by ssteveenn** [comment]
on last.fm, "tracks" usually refer to the number unique songs you've listened to, and not the total number of scrobbles. it's just a suggestion, though

**Comment by th0mk** [comment]
Technically speaking this is correct, since LastFM refers to all scrobbles as 'scrobbles' and to all unique tracks as 'tracks'
![image](https://user-images.githubusercontent.com/9088316/53698487-c0030180-3ddd-11e9-9e8a-b087f9aeeba9.png)
I've just pushed a fix.

**Comment by g--o** [comment]
@th0mk But I think we _are_ presenting the scrobbles

**Comment by th0mk** [comment]
Sorry, my response wasn't clear. I meant to say 'scrobbles' is the correct term and I've changed 'tracks' to 'scrobbles' in the bot.
